T284598 gutenberg search format
wikimedia/wikipediapreview-wordpress pull request #32
Opened 2021-09-03 13:43 UTC by hueitan

Phabricator Ticket: https://phabricator.wikimedia.org/T284598

The `prefix` search feature is implemented, the previous temp button of `Add` `Remove` are removed.

- [x] Mobile
- [x] prefix search
- [ ] fulltext search
- [ ] RTL
- [ ] Keyboard
- [ ] UI final tune

2021-09-08 08:13 UTC, hueitan commented on src/link/inline.js
> +			{ searchList?.length ? (
same to `searchList && searchList.length`, but I'm removing this now as it is not necessary here.

2021-09-10 19:48 UTC, stephanebisson requested changes
When you clear the search box with backspace it keeps the previous search results. It should probably go back to the initial (blank) state.

2021-09-10 19:48 UTC, stephanebisson commented on src/link/api.js
> +	// eslint-disable-next-line no-undef
I think the proper way to silent this warning is by telling eslint that this code will run in a browser so it understands that `XMLHttpRequest`, `document`, `window` etc are globals. 


In `.eslintrc`:
```
"env": {
        "browser": true
    }
```

2021-09-10 19:48 UTC, stephanebisson commented on src/link/inline.js
> +				.querySelectorAll( `.${ className }` )
It's not really the react way to access the DOM like this.

You're already keeping the hoveredIndex in a state so the code that renders the list items can add the `hovered` class to the right item. There's a bunch or re-rendering anyway.

2021-09-10 19:48 UTC, stephanebisson commented on src/link/inline.js
> +							// eslint-disable-next-line jsx-a11y/click-events-have-key-events
What is `jsx-a11y/click-events-have-key-events` trying to accomplish?

2021-09-13 09:36 UTC, hueitan commented
> When you clear the search box with backspace it keeps the previous search results. It should probably go back to the initial (blank) state.

Thanks for the feedback, all should be updated now.

2021-09-13 18:04 UTC, stephanebisson commented
> > When you clear the search box with backspace it keeps the previous search results. It should probably go back to the initial (blank) state.
> 
> Thanks for the feedback, all should be updated now.

Doesn't work for me. The only way I can clear the result is by typing a space character.

2021-09-13 18:20 UTC, stephanebisson requested changes
We should be able to do the following:
1. type in "Paris"
2. type ENTER without selecting any entry from the search results
since "paris" is a valid search result, it should just work, now it errors out

2021-09-14 07:38 UTC, hueitan commented
> We should be able to do the following:
> 
> 1. type in "Paris"
> 2. type ENTER without selecting any entry from the search results
>    since "paris" is a valid search result, it should just work, now it errors out

This is available now through the ENTER key,

the only thing missing clarification is the behaviour of how the typing/keyboard/mouse trigger the hover style/selection, should it behave the same as wikipedia search feature?

2021-09-14 19:24 UTC, stephanebisson commented
> the only thing missing clarification is the behaviour of how the typing/keyboard/mouse trigger the hover style/selection, should it behave the same as wikipedia search feature?

I think it works well as it is. I'll merge it so it can move forward to QA and design review.

2021-09-14 19:24 UTC, merged